rentaCar/Controllers/RentsController.cs
using rentaCar.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace rentaCar.Controllers
{
    public class RentsController : Controller
    {
        // GET: Rents
        rentaCarEntities db = new rentaCarEntities();
        public ActionResult Index()
        {
            var values = db.rent.ToList();
            return View(values);
        }

        //public ActionResult Details(int id) { }
        public ActionResult GetRent(int id)
        {
            var values = db.rent.Find(id);
            return View("GetRent", values);
        }
        public ActionResult EditRent(rent rent) 
        {
            var values = db.rent.Find(rent.Id);
            values.CustomerId = rent.CustomerId;
            values.CarId = rent.CarId;
            values.Day = rent.Day;
            values.RentalDate = rent.RentalDate;
            values.ReturnDate = rent.ReturnDate;
            values.Note = rent.Note;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult DeleteRent(int id)
        {
            var rent = db.rent.Find(id);
            db.rent.Remove(rent);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]

        public ActionResult NewRent()
        {
            List<SelectListItem> valuesCar = (from i in db.cars.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.LicensePlate,
                                               Value = i.Id.ToString(),
                                           }).ToList();   
            ViewBag.valueCar = valuesCar;
            List<SelectListItem> valuesCustomer = (from i in db.customers.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = i.FullName,
                                                       Value = i.Id.ToString(),
                                                   }).ToList();
            ViewBag.valueCustomer = valuesCustomer;
            return View();
        }

        [HttpPost]

        public ActionResult NewRent(rent rent)
        {
            var car = db.cars.Where(m => m.Id == rent.cars.Id).FirstOrDefault();
            rent.cars = car;
            var customer = db.customers.Where(m => m.Id == rent.customers.Id).FirstOrDefault();
            rent.customers = customer;
            db.rent.Add(rent);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

rentaCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("RentACar", "Index", "Rents", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Gezintiyi aç/kapat" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Giriş", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

rentaCar/Views/Shared/_MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/dist/css/lightbox.css">
    <script src="/dist/js/lightbox.js"></script>
    <link href="~/Content/c3.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/c3.min.js"></script>
    <script src="~/Scripts/d3.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">rentaCAR</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Ana Sayfa</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Araçlar<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/Cars/Index/">Tüm Araçlar</a></li>
                        <li><a href="/OnRentCars/OnRentCars/">Kiradaki Araçlar</a></li>
                        <li><a href="/AvailableCars/AvailableCars/">Müsait Araçlar</a></li>
                    </ul>
                </li>
                <li><a href="/Customers/Index/">Müşteriler</a></li>
                <li><a href="/Rents/Index/">Kiralamalar</a></li>
                <li><a href="/Login/Logout">Çıkış Yap</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">

        @RenderBody();

    </div>



    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    

</body>
</html>