rentaCar/Models/Entities/cars.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentaCar.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cars()
        {
            this.rent = new HashSet<rent>();
        }
    
        public int Id { get; set; }
        public string LicensePlate { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int ProductYear { get; set; }
        public string Color { get; set; }
        public int km { get; set; }
        public string CarType { get; set; }
        public byte RentState { get; set; }
        public decimal DailyPrice { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent> rent { get; set; }
    }
}

rentaCar/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rentaCar.Models.Entities;

namespace rentaCar.Controllers
{
    public class CarsController : Controller
    {
        rentaCarEntities db = new rentaCarEntities();
        // GET: Cars
        public ActionResult Index() 
        {
            var values = db.cars.ToList();
            return View(values);
        }

        [HttpGet]

        public ActionResult NewCar() 
        {
            return View();
        }

        [HttpPost]

        public ActionResult NewCar(cars car) 
        {
            db.cars.Add(car);
            db.SaveChanges();


            return RedirectToAction("Index");
        }

        public ActionResult DeleteCar(int id)
        {
            var car = db.cars.Find(id);
            db.cars.Remove(car);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        

        public ActionResult OnRentCars()
        {
            var values = db.cars.ToList();
            return View(values);
        }

        public ActionResult AvailableCars()
        {
            var values = db.cars.ToList();
            return View(values);
        }

        public ActionResult GetCar(int id)
        {
            var values = db.cars.Find(id);
            return View("GetCar",values);
        }

        public ActionResult EditCar(cars car)
        {
            var values = db.cars.Find(car.Id);
            values.LicensePlate = car.LicensePlate;
            values.Brand = car.Brand;
            values.Model = car.Model;
            values.ProductYear = car.ProductYear;
            values.Color = car.Color;
            values.km = car.km;
            values.CarType = car.CarType;
            values.RentState = car.RentState;
            values.DailyPrice = car.DailyPrice;
            db.SaveChanges();

            return RedirectToAction("Index");

        }

    }
}

rentaCar/Controllers/CarsControllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using rentaCar.Models.Entities;

namespace rentaCar.Controllers
{
    public class CarsController : Controller
    {
        rentaCarEntities db = new rentaCarEntities();
        // GET: Cars
        public ActionResult Index()
        {
            var values = db.cars.ToList();
            ViewBag.Values = values;
            return View(values);
        }

        public ActionResult DeleteCar(int id)
        {
            var rent = db.rent.FirstOrDefault(x => x.CarId == id);
            if (rent != null)
            {
                ViewBag.message = "Kiralanmış bir aracı silemezsin!";
                return RedirectToAction("Index");

            }
            else
            {
                var car = db.cars.Find(id);
                db.cars.Remove(car);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

        }



        [HttpPost]
        //[ValidateInput(false)]
        public ActionResult EditCar(cars car)
        {
            var values = db.cars.Find(car.Id);
            if (car.ImageFile != null)
            {
                if (System.IO.File.Exists(Server.MapPath(car.Image)))
                {
                    System.IO.File.Delete(Server.MapPath(car.Image));
                }
                WebImage img = new WebImage(car.ImageFile.InputStream);
                FileInfo imginfo = new FileInfo(car.ImageFile.FileName);
                string filename = car.ImageFile.FileName;
                img.Save("/Image/" + filename);

                values.Image = "/Image/" + filename;
            }

            values.LicensePlate = car.LicensePlate;
            values.Brand = car.Brand;
            values.Model = car.Model;
            values.ProductYear = car.ProductYear;
            values.Color = car.Color;
            values.km = car.km;
            values.CarType = car.CarType;
            values.RentState = car.RentState;
            values.DailyPrice = car.DailyPrice;
            db.SaveChanges();

            return RedirectToAction("Index");

        }
        [ValidateInput(false)]
        public ActionResult DeleteImage(int id)
        {
            var values = db.cars.Find(id);

            if (!string.IsNullOrEmpty(values.Image))
            {
                if (System.IO.File.Exists(Server.MapPath(values.Image)))
                {
                    System.IO.File.Delete(Server.MapPath(values.Image));
                }
                values.Image = "/Image/no-image.png";
                db.SaveChanges();
                return RedirectToAction("Getcar/" + values.Id, "GetCar");
            }

            return RedirectToAction("Getcar/" + values.Id, "GetCar");
        }

    }
}

rentaCar/Controllers/CarsControllers/GetCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rentaCar.Models.Entities;
namespace rentaCar.Controllers.CarsControllers
{
    public class GetCarController : Controller
    {
        rentaCarEntities db = new rentaCarEntities();
        // GET: GetCar
        public ActionResult GetCar(int id)
        {
            var values = db.cars.Find(id);
            return View("GetCar", values);
        }
    }
}

rentaCar/Controllers/CarsControllers/NewCarController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using rentaCar.Models.Entities;

namespace rentaCar.Controllers
{
    public class NewCarController : Controller
    {
        rentaCarEntities db = new rentaCarEntities();
        // GET: NewCar
        //[HttpGet]
        //public ActionResult NewCar()
        //{
        //    return View();
        //}
        [HttpGet]
        public ActionResult NewCar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewCar(cars car)
        {   if(car.ImageFile == null)
            {
                car.Image = "Null";
            }
            if (car.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(car.ImageFile.FileName);
                string extension = Path.GetExtension(car.ImageFile.FileName);
                fileName = fileName + extension;
                car.Image = "/Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("/Image/"), fileName);
                car.ImageFile.SaveAs(fileName);
            }
            car.RentState = 1;
            db.cars.Add(car);
            db.SaveChanges();


            return RedirectToAction("../cars/index");
        }
    }
}

rentaCar/Controllers/CarsControllers/OnRentCarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using rentaCar.Models.Entities;

namespace rentaCar.Controllers.CarsControllers
{
    public class OnRentCarsController : Controller
    {
        rentaCarEntities db = new rentaCarEntities();
        // GET: OnRentCars
        public ActionResult OnRentCars()
        {
            List<SelectListItem> valuesCar = (from i in db.cars.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = i.LicensePlate,
                                                  Value = i.Id.ToString(),
                                              }).ToList();
            ViewBag.valueCar = valuesCar;
            List<SelectListItem> valuesCustomer = (from i in db.customers.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = i.FullName,
                                                       Value = i.Id.ToString(),
                                                   }).ToList();
            ViewBag.valueCustomer = valuesCustomer;

            //var values = db.cars.ToList();
            //ViewBag.values = values;
            var values = db.cars.ToList();
            var aa = from c in db.cars
                     where (c.RentState == 1)
                     select c;
            var a = aa.Count();
            var bb = from c in db.cars
                     where (c.RentState == 0)
                     select c;

            var b = bb.Count();

            var rentedCarIdsQuery =
                from c in db.cars
                join r in db.rent on c.Id equals r.CarId into rentedCars
                where rentedCars.Any(r => r.CarId == c.Id)
                select c;
            var w = rentedCarIdsQuery.Count();

            var query =
                from c in db.cars
                where !rentedCarIdsQuery.Contains(c) ||
                      (c.RentState == 1 && !db.rent.Any(r => r.CarId == c.Id))
                select c;

            var y = query.Count();

            ViewBag.a = a;
            ViewBag.b = b;
            ViewBag.c = w;
            ViewBag.d = a - y;
            return View();
        }
    }
}

rentaCar/Views/Cars/GetCar.cshtml
@model rentaCar.Models.Entities.cars
@{
    ViewBag.Title = "GetCar";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("EditCar", "Cars", FormMethod.Post))
{
    <div class="form-horizontal">
        <h4>ARAÇ DÜZENLE</h4>
        <hr />
        <div class="form-group">
            <label class="control-label col-sm-2">ID</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.Id, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Plaka</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.LicensePlate, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2">Marka</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.Brand, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2">Model</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.Model, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2">Yıl</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.ProductYear, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2">Renk</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.Color, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2">KM</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.km, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Araç Tipi</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.CarType, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Kira Uygunluk</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.RentState, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Günlük Ücret</label>
            @*@Html.LabelFor(k => k.LicensePlate)*@
            <div class="col-sm-5">
                @Html.TextBoxFor(k => k.DailyPrice, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-warning">Güncelle</button>
        </div>
    </div>



}

rentaCar/Views/Cars/Index.cshtml
@using rentaCar.Models.Entities

@model IEnumerable<rentaCar.Models.Entities.cars>

@*@model List<cars>*@
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    WebGrid grid = new WebGrid(Model);
}


<div class="container">
    <h4>Tüm Araçlar</h4>
    <hr />
    <div id="gallery">
        @grid.GetHtml(
             tableStyle: "table-bordered col-md-12 text-center",
             columns: grid.Columns(
                     grid.Column(format: @<a href="@item.Image" class="demo" 
                                             -lightbox="example-1"><img src="@Href(item.Image)" class="example-image" width="100" height="100" /></a> ),
grid.Column("Id", "ID"),
grid.Column("LicensePlate", "Plaka"),
grid.Column("Brand", "Marka"),
grid.Column("Model", "Model"),
grid.Column("ProductYear", "Yıl"),
grid.Column("Color", "Renk"),
grid.Column("km", "KM"),
grid.Column("CarType", "Araç Tipi"),
grid.Column("RentState", "Kira Uygunluk"),
grid.Column("DailyPrice", "Günlük Ücret"),
grid.Column("Düzenle", format: @<text> <a href="/GetCar/GetCar/@item.Id" class="btn btn-info">Düzenle</a> </text>),
grid.Column("Sil", format: @<text> <a href="/Cars/DeleteCar/@item.Id" class="btn btn-danger" id="del"> Sil</a> </text>)

)
)
    </div>

    <div>
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#NewCar">Yeni Araç</button>
    </div>
</div>

<div class="modal" id="NewCar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Yeni Araç</h4>
            </div>
            <form class="form-horizontal" method="post" action="/NewCar/NewCar" enctype="multipart/form-data">
                <div class="form-group">
                    <label class="control-label col-sm-2">Plaka</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="LicensePlate" id="plate" onkeyup="validatePlate()" />
                        <span id="plateError" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Marka</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="Brand" id="brand" onkeyup="validateBrand()" />
                        <span id="brandError" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Model</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="Model" id="model" onkeyup="validateModel" />
                        <span id="modelError" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Yıl</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="ProductYear" id="year" />
                        <span id="yearError" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Renk</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="Color" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Kilometre</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="km" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Araç Tipi</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="CarType" id="type" />
                        <span id="typeError" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Günlük Ücret</label>
                    <div class="col-sm-5">
                        <input type="text" class="form-control" name="DailyPrice" id="price" />
                        <span id="priceError" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2">Fotoğraf</label>
                    <div class="col-sm-5">
                        <input type="file" class="form-control" name="ImageFile" id="image" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button class="btn btn-info" onclick="return validateForm()">Ekle</button>
                        <span id="submitError" class="textDanger"></span>
                    </div>
                </div>
            </form>
            @if (ViewBag.Message != null)
            {
                <script type="text/javascript">

                    window.onload = function () {
                        alert("@ViewBag.Message");
                    };
                </script>

            }
        </div>
    </div>
</div>



<script>
    function validatePlate() {
        var plate = document.getElementById('plate').value;
        if (plate == 0) {
            plateError.innerHTML = 'Alan boş bırakılamaz!';
            return false;
        }
        plateError.innerHTML = '';
        return true;
    }
    function validateBrand() {
        var brand = document.getElementById('brand').value;
        if (brand == 0) {
            brandError.innerHTML = 'Alan boş bırakılamaz!';
            return false;
        }
        brandError.innerHTML = '';
        return true;
    }
    function validateModel() {
        var model = document.getElementById('model').value;
        if (model == 0) {
            modelError.innerHTML = 'Alan boş bırakılamaz!';
            return false;
        }
        modelError.innerHTML = '';
        return true;
    }
    function validateYear() {
        var year = document.getElementById('year').value;
        if (year == 0) {
            yearError.innerHTML = 'Alan boş bırakılamaz!';
            return false;
        }
        yearError.innerHTML = '';
        return true;
    }
    function validateType() {
        var type = document.getElementById('type').value;
        if (type == 0) {
            typeError.innerHTML = 'Alan boş bırakılamaz!';
            return false;
        }
        typeError.innerHTML = '';
        return true;
    }
    function validatePrice() {
        var price = document.getElementById('price').value;
        if (type == 0) {
            priceError.innerHTML = 'Alan boş bırakılamaz!';
            return false;
        }
        priceError.innerHTML = '';
        return true;
    }

    function validateForm() {
        if (!validatePlate() || !validateBrand() || !validateModel() || !validateYear() || !validateType() || !validatePrice()) {
            submitError.innerHTML = 'HATA';
            return false;
        }
    }

</script>


@*<div class="container">
        <h4>TÜM ARAÇLAR</h4>
        <hr />
        <table class="table table-bordered"
                <tr class="text-center">
                    <th>ID</th>
                    <th>License Plate</th>
                    <th>Brand</th>
                    <th>Model</th>
                    <th>Product Year</th>
                    <th>Color</th>
                    <th>Km</th>
                    <th>Car Type</th>
                    <th>Rent State</th>
                    <th>Daily Price</th>
                    <th>Güncelle</th>
                    <th>Sil</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var x in Model)
                {
                    <tr class="text-center">
                        <td>@x.Id</td>
                        <td>@x.LicensePlate</td>
                        <td>@x.Brand</td>
                        <td>@x.Model</td>
                        <td>@x.ProductYear</td>
                        <td>@x.Color</td>
                        <td>@x.km</td>
                        <td>@x.CarType</td>
                        <td>@if(@x.RentState==0)
                        {
                            <p>Uygun</p>
                        }else{
                            <p>Uygun Değil</p>
                        }
                        </td>
                        <td>@x.DailyPrice</td>
                        <td>
                            <a href="/Cars/GetCar/@x.Id" class="btn btn-info">Güncelle</a>
                        </td>
                        <td>
                            <a href="/Cars/DeleteCar/@x.Id" class="btn btn-danger">Sil</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <a href="/Cars/NewCar/" class="btn btn-success">Araç Ekle</a>
    </div>*@

rentaCar/Views/Cars/NewCar.cshtml
@{
    ViewBag.Title = "NewCar";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-horizontal" method="post">
    <h4>YENİ ARAÇ</h4>
    <hr />
    <div class="form-group">
        <label class="control-label col-sm-2">Plaka</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="LicensePlate" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Marka</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="Brand" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Model</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="Model" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Yıl</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="ProductYear" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Renk</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="Color" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Kilometre</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="km" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Araç Tipi</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="CarType" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2">Günlük Ücret</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="DailyPrice" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button class="btn btn-info">Ekle</button>
        </div>
    </div>
</form>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

rentaCar/Views/Cars/OnRentCars.cshtml
@using rentaCar.Models.Entities

@model List<cars>
@{
    ViewBag.Title = "OnRentCars";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="container">
    <h4>KİRADA OLAN ARAÇLAR</h4>
    <hr />
    <table class="table table-bordered">
        <thead>
            <tr class="text-center">
                <th>ID</th>
                <th>License Plate</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Product Year</th>
                <th>Color</th>
                <th>Km</th>
                <th>Car Type</th>
                <th>Rent State</th>
                <th>Daily Price</th>
                @*<th>Güncelle</th>
                <th>Sil</th>*@

            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                if (x.RentState == 1)
                {
                    <tr class="text-center">
                        <td>@x.Id</td>
                        <td>@x.LicensePlate</td>
                        <td>@x.Brand</td>
                        <td>@x.Model</td>
                        <td>@x.ProductYear</td>
                        <td>@x.Color</td>
                        <td>@x.km</td>
                        <td>@x.CarType</td>
                        <td>@x.RentState</td>
                        <td>@x.DailyPrice</td>
                    </tr>
                }

            }
        </tbody>
    </table>
</div>